### ISSUE TITLE
Transparency Webgl Bug

### ISSUE THREAD

**Issue by sinfulspartan** [Unity-Technologies/com.unity.toonshader#357] opened 2024-05-10 20:53 UTC
**Describe the bug**
On webgl builds the transparency setting doesn't work.

**To Reproduce**
Just build to webgl with any transparency setting.
It works in standalone and editor.

**Expected behavior**
Model should be transparent, same as in standalone build.

**Screenshots**
Standalone
![image](https://github.com/Unity-Technologies/com.unity.toonshader/assets/89873705/1131f337-e346-436c-a78b-8993f9244a08)

Web
![image](https://github.com/Unity-Technologies/com.unity.toonshader/assets/89873705/74f67ecc-ae85-4aa2-8c77-ce53e1a3ec01)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.201 (Official Build) (64-bit)

**Comment by H3idi-X** [comment] 2024-05-11 12:30
Thank you for choosing Unity Toon Shader.
We have attempted to reproduce the issue using Unity version 2022.3.28f1, but it appears that both the Built-in RP and Universal-RP are rendering translucent objects. 
If the semi-transparent objects are not displaying correctly in the "sample" scene [included with Toon Shader](https://docs.unity3d.com/Packages/com.unity.toonshader@0.10/manual/sample-instlation.html), there may be an issue with your environment. Alternatively, it may be attributed to differences in the build settings.
Throughout our testing, we did not encounter any difficulties with the display of semi-transparent objects. Nevertheless, it is important to note that WebGL may not render precisely the same as in the Editor or Standalone versions due to various limitations, even after switching platforms.
![image](https://github.com/Unity-Technologies/com.unity.toonshader/assets/4477357/e47ff566-a510-47fd-b221-a94db0caa4ad)

**Comment by sinfulspartan** [comment] 2024-05-11 17:06
@H3idi-X 
Here are the settings I'm using:
![image](https://github.com/Unity-Technologies/com.unity.toonshader/assets/89873705/3aa765f4-985a-4a98-81de-8a3548443d01)
![image](https://github.com/Unity-Technologies/com.unity.toonshader/assets/89873705/2eaad3f4-2bd4-4eff-b6ea-749fd0753af8)

I'm on Unity 2022.3.0. Are there any other settings that would affect the transparency?

**Comment by H3idi-X** [comment] 2024-05-11 19:10
We apologize for the inconvenience, but please try the following as in the previous answer.
"sample" scene [included with Toon Shader](https://docs.unity3d.com/Packages/com.unity.toonshader@0.10/manual/sample-instlation.html),

**Comment by sinfulspartan** [comment] 2024-05-11 21:02
@H3idi-X 
Yes. The demo scene transparency does not work in webgl.
![image](https://github.com/Unity-Technologies/com.unity.toonshader/assets/89873705/89d1b79e-b14f-4a8e-aa6f-20a2c7ba66f9)

**Comment by H3idi-X** [comment] 2024-05-13 23:54
Hello,
We have not yet succeeded in reproducing the issue.
Could you please provide us with more detailed information, including the following:

- Unity Version
- Render Pipeline (Built-in RP or URP)
- Toon Shader Package version

Thank you.

**Comment by sinfulspartan** [comment] 2024-05-14 00:29
Unity 2022.3.0
URP 14.0.7
Toon 0.10.0

**Comment by sinfulspartan** [comment] 2024-05-16 23:00
@H3idi-X 
Unity 2022.3.0
URP 14.0.7
Toon 0.10.0

**Comment by H3idi-X** [comment] 2024-05-17 11:16
Hello,

This week, we tested Unity 2022.3.0f1, URP, WebGL, and UTS on several PCs and succeeded in reproducing the issue on one device. It appears that the shader is falling back to other shaders instead of UTS as you see textures and some detail on the objects are also strange in the screen shot.

We confirmed the same scene working correctly by updating the Unity version to 2022.3.29f1. We suspect that there is an issue with the shader compatibility check in Unity version 2022.3.0f1, which has been resolved in version 2022.3.29f1.

Could you please try updating to this new Unity version?

Thank you.

**Comment by sinfulspartan** [comment] 2024-05-17 13:45
@H3idi-X 
That fixed the issue.
![image](https://github.com/Unity-Technologies/com.unity.toonshader/assets/89873705/1c8bc7fc-1546-4346-942f-4ad2e01df709)

**Comment by H3idi-X** [comment] 2024-05-17 19:03
Good to hear!
We close this issue.

**Closed by H3idi-X** 2024-05-17 19:03 UTC
