### ISSUE TITLE
Weird Bloom Artifact with Synty Assets when using Toon Shader

### ISSUE THREAD

**Issue by Brainshack** [Unity-Technologies/com.unity.toonshader#351] opened 2024-04-13 04:11 UTC
**Describe the bug**
When using the Toon Shader with some of Synty Studios Assets (from the SciFi Worlds Pack), some edges and faces cause weird brigt bloom, when enabling bloom (See Screenshot). The same Post processing Settings work flawlessly using the URP Lit Shader. This is done in a DOTS SubScene using [this branch](https://github.com/Unity-Technologies/com.unity.toonshader/tree/dev/dots-instancing-urp). The Material has no Emissive Maps or properties.

**Screenshots**
![image](https://github.com/Unity-Technologies/com.unity.toonshader/assets/456234/87483324-3681-4f7a-a4df-a20c505fb895)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Unity 2023.3
 - Entities Graphics 1.2
 - Toon Shader dev/dots-instancing-urp branch

**Comment by H3idi-X** [comment] 2024-04-16 20:25
@Brainshack Thanks for the feedback. The branch is on development now. But as far as we checked, there is no side effect for it and we were not able to reproduce the issue. Will you please provide more detailed information about this issue? BTW, We will delete the branch after it get merged into our main branch like we do as usual.

**Comment by H3idi-X** [comment] 2024-04-20 01:05
We are writing to inform you that we will be closing this particular issue as it has not been reproducible on our end. Should you be able to provide us with more information or reproducible samples in the future, please do not hesitate to reopen the issue, and we will be more than willing to revisit it.

Thank you for your understanding and cooperation.

Best regards,

**Closed by H3idi-X** 2024-04-20 01:05 UTC
