### ISSUE TITLE
Magenta on Android.

### ISSUE THREAD

**Issue by Fejuto** [Unity-Technologies/com.unity.toonshader#239] opened 2022-09-02 02:30 UTC
**Describe the bug**
When running on an Android device, all objects using the toon shader show as magenta -- the magenta Unity shows objects as when there is a shader issue. 

**To Reproduce**
1. Create new Unity URP project in Unity 2022.1.14f1
2. Add the toon package 0.8.1-preview. Install the URP examples. Demo scenes look fine in the Unity editor.
3. Make an Android build containing any example scene
4. When the game launches on the phone, the objects with the toon shader on them show as magenta.

**Smartphone (please complete the following information):**
 - Device: tried on Pixel 3a, and Poco F3. Both reproduce
 - OS: Android

**Comment by H3idi-X** [comment] 2022-09-02 11:37
Hello, Thanks for reporting.

We tried to reproduce the issue. But the result was different.


- Vulkan: sample worked but slow.
- Open GL ES3: UTS materials were not shown but not magenta.
- Open GL ES2: Unable to build.

Which graphics API did you choose?

We used:

- Unity Toon Shader version 0.8.1-preview
- Unity Version 2022.1.15f1
- The device is Pixel 6XL

**Comment by Fejuto** [comment] 2022-09-03 00:36
The magenta I got when building for Open GL ES3. Because of your comment I also tried Vulkan and got different behaviour, but still faulty. Made a video for you: https://drive.google.com/uc?id=1AXl4sxzkI_YTJlgRlowI8vNDoSb5REIg.

**Comment by tangx246** [comment] 2022-09-05 18:19
Just wanted to add to this. Following the reproduction steps:
1. Create new Unity URP project in Unity 2022.1.15f1
2. Add the toon package 0.8.1-preview. Install the URP examples. Demo scenes look fine in the Unity editor.
3. Build for Windows / WebGL
4. When game launches, objects with toon shader in Windows are magenta. In WebGL, not shown at all

The shader works fine in the editor, though. Also, when we changed to Toon Shader 0.7.5-preview (and adjusted materials appropriately), builds work fine again

**Comment by H3idi-X** [comment] 2022-09-06 01:09
Thanks you both for giving additional information.  We are currently investigating if the _shader package requirements_ are working correctly.

**Comment by H3idi-X** [comment] 2022-09-07 01:01
Hi, Perhaps because our devices are different from yours, we have not yet succeeded to reproduce the phenomenon of the URP material becoming Magenta on Android and WebGL.
Just to be sure, could you provide  us  the projects that produce this issue?

**Comment by tangx246** [comment] 2022-09-07 04:42
Hi.

Here is the project: https://github.com/tangx246/toonshadermagenta. It was created using the reproduction steps as above, and built using some randomly chosen sample scene.

In Editor - everything works as normal: 
![image](https://user-images.githubusercontent.com/4165560/188789784-7c6048b3-80b5-421c-ae7c-4f5ee39bedd1.png)
Built for Windows - my mistake. Looks like it only turns magenta with strict shader variant matching, but looks normal otherwise: 
![image](https://user-images.githubusercontent.com/4165560/188790263-4ab19b17-9065-4ba0-b6d6-43eee6158f0d.png)
![image](https://user-images.githubusercontent.com/4165560/188790142-8a7d337c-9746-41bc-8ea6-08e793243a4d.png)

Built for WebGL (run on Chrome 105.0.5195.53) - model completely missing: 
![image](https://user-images.githubusercontent.com/4165560/188789752-d7260b23-ff99-4aa3-af8f-d00569744878.png)

Regardless, it is still a regression for WebGL builds, as Toonshader 0.7.5-preview works for WebGL

**Comment by H3idi-X** [comment] 2022-09-07 05:19
Thank you very much, @tangx246!. The result of WebGL is the same to our result. We fixed that locally.

**Comment by H3idi-X** [comment] 2022-09-07 08:46
Hi, we haven’t succeeded to reproduce magenta materials in both Android and WebGL though, we fixed the issue that the URP shader didn’t work on WebGL, GLES 3.0. The fix will be included in the next release 0.8.2-preview, which is supposed to be released in several days. If you want to test the fix, you can clone our development/v1 branch now.  Thanks for your cooperation.

**Comment by H3idi-X** [comment] 2022-09-07 08:58
Oh, forgot to mention one thing, we haven't checked strict shader variant matching yet.

**Comment by H3idi-X** [comment] 2022-09-09 10:12
Hi, we released 0.8.2-preview. Will you please try that one?

**Comment by tangx246** [comment] 2022-09-09 18:07
Looks like it's now working on WebGL builds :+1: Thanks for your efforts!
![image](https://user-images.githubusercontent.com/4165560/189416037-0e2ae8ae-f24e-49fd-ac6b-add5434a2827.png)

I am skipping Windows builds, as strict shader variant matching was only turned out to attempt to debug the WebGL build. Since it works without it, it is low priority for us.

**Comment by H3idi-X** [comment] 2022-09-09 21:11
We are relieved to hear that. Thanks, @tangx246.
Could you share your result, @Fejuto ?

**Comment by H3idi-X** [comment] 2022-09-13 21:22
Hi,
We would close this issue if there is no further reports about magenta materials in a few days.
@Fejuto How is your case?

**Closed** 2022-09-19 12:03 UTC

**Comment by Fejuto** [comment] 2022-09-24 04:47
Android build now works!

**Comment by H3idi-X** [comment] 2022-09-24 06:52
Thanks for confirming.
