### ISSUE TITLE
Error when creating/importing material that prevents outline from working

### ISSUE THREAD

**Issue by scwilbanks** [Unity-Technologies/com.unity.toonshader#305] opened 2023-04-23 17:39 UTC
**Describe the bug**
I installed the latest version of package into my URP project and tried to create a new material but I received the following two errors in the console. I received the same errors when importing the URP sample scenes.

`[Worker0] Failed to create MaterialEnum, enum UnityEditor.Rendering.HighDefinition.TransparentCullMode not found

[Worker0] Failed to create material drawer Enum with arguments 'UnityEditor.Rendering.HighDefinition.TransparentCullMode'

`

The features of the shader seem to work correctly except for the outline. The outline simple does not show up despite enabling it in the shader settings.

**To Reproduce**
1. Install toonshader package into URP project
2. Create material or import sample scenes
3. Error

**Desktop**
 - Version 2021.3.21f1
 - URP 12.1.10

**Comment by H3idi-X** [comment] 2023-04-24 00:16
Could you provide us the specific Unity Toon Shader version, 0.9.2-preview?

**Comment by scwilbanks** [comment] 2023-04-24 00:19
Yes, Version 0.9.2-preview

**Comment by H3idi-X** [comment] 2023-04-24 05:16
Hi, Thanks for reporting the issues.
We reproduced both of them, one is the warnings and the other is outline.
We are on the investigation into them.

**Comment by H3idi-X** [comment] 2023-04-26 00:19
Outline is enabled but the default width = 0.0.  Could you try setting **Outline Width**? 

>  The outline simple does not show up despite enabling it in the shader settings.

**Comment by scwilbanks** [comment] 2023-04-27 03:15
Changing the outline width setting doesn't seem to have any effect.

**Comment by H3idi-X** [comment] 2023-04-27 04:08
Oh! Sorry, we found outline works in projects which are upgraded from 2020.x to 2021.3.21f1. But it doesn't in projects originally created in 2021.3.21f1. We contiue to investgate the causes.

**Comment by H3idi-X** [comment] 2023-04-28 05:37
Hi, The following warrning is fixed at the next release, but this is not releated to the outline issue.
`[Worker0] Failed to create MaterialEnum, enum UnityEditor.Rendering.HighDefinition.TransparentCullMode not found

To show outline, will you please change the Depth Priming Mode in the Renderer asset? By design, outlines won't be rendered in URP.
We will add this notice to the next reelase docs.

![image](https://user-images.githubusercontent.com/4477357/235063226-9a1defef-c26f-4549-b64a-bd53328c80e3.png) 
![image](https://user-images.githubusercontent.com/4477357/235063254-e5de7555-97d8-4085-bfda-35580855b0ac.png)

**Comment by H3idi-X** [comment] 2023-05-03 01:45
Hi, we fixed the following warnings and releasaed 0.9.4-preview yesterday.
Will you please try that one?.
Please be noticed the outline issue is not caused by these warnings. It is related to  Depth Priming Mode setting we mentiond in above.
We added notiice into the [document](https://docs.unity3d.com/Packages/com.unity.toonshader@0.9/manual/Known-issue.html).

Thank you!

[Worker0] Failed to create MaterialEnum, enum UnityEditor.Rendering.HighDefinition.TransparentCullMode not found
[Worker0] Failed to create material drawer Enum with arguments 'UnityEditor.Rendering.HighDefinition.TransparentCullMode'

**Comment by scwilbanks** [comment] 2023-05-04 04:37
Yes, changing the Depth Priming Mode to disabled let's the outline show. Thank you!

**Comment by H3idi-X** [comment] 2023-05-08 05:08
Thanks for the confirmation.
We close this issue.

**Closed by H3idi-X** 2023-05-08 05:08 UTC
