### ISSUE TITLE
Compilation Errors in 0.9.0

### ISSUE THREAD

**Issue by CDTR-MattConroy** [Unity-Technologies/com.unity.toonshader#289] opened 2023-03-23 10:24 UTC
**Describe the bug**
There are compilation errors after importing 0.9.0

**To Reproduce**
1. Install version 0.9.0
2. Observe errors in console

**Expected behavior**
Be able to install 0.9.0 without errors

**Screenshots**
<img width="551" alt="image" src="https://user-images.githubusercontent.com/120377840/227174246-9a0fe0ad-4ecb-46c6-8d7b-d1e2f3e71de1.png">

**Desktop:**
 - OS: Windows 11
 - Version 22H2

**Additional context**
The errors are regarding AnalyticsResult and suggest installing Unity Analytics in the Package Manager. Doing so does not resolve the issue. If the Toon Shader package is reliant on Unity Analytics then should it be a dependency?

**Comment by H3idi-X** [comment] 2023-03-24 00:13
Thank you for using Unity Toon Shader.
The 0.9.x-preview is compatible with Unity versions described in [System-Requirements](https://docs.unity3d.com/Packages/com.unity.toonshader@0.9/manual/System-Requirements.html). We apologize for the inconvenience. Currently, there is no way to handle these requirements in the Package Manager.

**Comment by sindharta** [comment] 2023-03-24 02:13
@CDTR-MattConroy What is the version of Unity that you are using ?

**Comment by sindharta** [comment] 2023-03-27 02:11
@yuki4080  is right, and wrapping analytics code inside  `ENABLE_CLOUD_SERVICES_ANALYTICS` is actually a requirement as mentioned in [Analytics documentation](https://docs.unity3d.com/ScriptReference/Analytics.Analytics.html).

Thank you for the report, and we'll fix this.

**Comment by CDTR-MattConroy** [comment] 2023-03-28 15:19
Thanks @sindharta. How soon can we expect an updated release?

For reference, I was using Unity 2022.2.5f1, but after upgrading to 2022.2.12f1 the errors are still present.

**Comment by sindharta** [comment] 2023-03-29 02:00
It should be "soon", so please stay tuned.

If possible, can you please share what platform you are targeting ?

**Comment by CDTR-MattConroy** [comment] 2023-03-29 08:12
Excellent, thanks, I'll keep an eye out. 

I'm currently targeting Windows 64 Standalone.

**Comment by sindharta** [comment] 2023-03-29 09:36
Hm, this should not happen if you are targeting Windows 64 Standalone with  2022.2.12f1.
Is the error that you are having right now the same as before ?

<img alt="image" width="800" src="https://user-images.githubusercontent.com/120377840/227174246-9a0fe0ad-4ecb-46c6-8d7b-d1e2f3e71de1.png">

**Comment by Xasa7980** [comment] 2023-04-05 15:55
I have the same issue with unity 2021.3.15f1 but mine is a bit diferent, and i don't know what's going on but hope this will get fixed because is a wonderful asset 
![image](https://user-images.githubusercontent.com/99562106/230136427-ab17e1de-7e66-40a6-8b0b-42d7ea9773de.png)

**Comment by sindharta-tanuwijaya** [comment] 2023-04-05 23:46
For Unity 2021, `com.unity.toonshader@0.9.x` needs Unity 2021.3.19 or later.
Please see the [requirements](https://docs.unity3d.com/Packages/com.unity.toonshader@0.9/manual/System-Requirements.html) section on our documentation for more details.

**Comment by sindharta** [comment] 2023-04-05 23:47
For Unity 2021, `com.unity.toonshader@0.9.x` needs Unity 2021.3.19 or later.
Please see the [requirements](https://docs.unity3d.com/Packages/com.unity.toonshader@0.9/manual/System-Requirements.html) section on our documentation for more details.

**Comment by sindharta** [comment] 2023-04-05 23:49
And, `com.unity.toonshader@0.9.1` has been released, which fixes the issue reported in this thread (due to Analytics).
Please feel free to reopen the issue if it still persists for you.

**Comment by Xasa7980** [comment] 2023-04-07 15:55
> For Unity 2021, `com.unity.toonshader@0.9.x` needs Unity 2021.3.19 or later. Please see the [requirements](https://docs.unity3d.com/Packages/com.unity.toonshader@0.9/manual/System-Requirements.html) section on our documentation for more details.

So i can't use com.unity.toonshader in any version for unity version 2021.3.15?

**Comment by sindharta** [comment] 2023-04-10 01:13
You can use `com.unity.toonshader@0.8.x` or earlier

**Comment by plyoung** [comment] 2023-05-14 12:11
Unity 2022.2.19. Update to UTC 0.9.4 and now I get this error about the analytics.

Library\PackageCache\com.unity.film-internal-utilities@0.18.4-preview\Runtime\Scripts\Analytics\AnalyticsSender.cs(39,9): error CS1069: The type name 'AnalyticsResult' could not be found in the namespace 'UnityEngine.Analytics'. This type has been forwarded to assembly 'UnityEngine.UnityAnalyticsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' Enable the built in package 'Unity Analytics' in the Package Manager window to fix this error.

**Comment by plyoung** [comment] 2023-05-27 07:49
So, is the shader supposed to work now even if the analytics is disabled? I still get the error message from film internal.
UTS 0.9.4-preview, Unity 2022.2.19.

`Library\PackageCache\com.unity.film-internal-utilities@0.18.4-preview\Runtime\Scripts\Analytics\AnalyticsSender.cs(39,9): error CS1069: The type name 'AnalyticsResult' could not be found in the namespace 'UnityEngine.Analytics'. This type has been forwarded to assembly 'UnityEngine.UnityAnalyticsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' Enable the built in package 'Unity Analytics' in the Package Manager window to fix this error.`

**Comment by H3idi-X** [comment] 2023-05-27 12:08
Hi, Will you please provide us more detailed information about this issue?.
As far as we see there is no errors UTS 0.9.4-preview, Unity  2022.2.19 when Editor Analytics is disabled. 
<img width="1686" alt="Screen Shot 2023-05-27 at 21 06 01" src="https://github.com/Unity-Technologies/com.unity.toonshader/assets/4477357/fed6da6d-adaa-48e4-84a1-d7b664be1e37">


> So, is the shader supposed to work now even if the analytics is disabled? I still get the error message from film internal.
> UTS 0.9.4-preview, Unity 2022.2.19.

**Comment by plyoung** [comment] 2023-05-27 18:44
I've just created a new  URP 3D project with Unity 2022.2.19 and unstalled UTS via com.unity.toonshader
All fine...

Then I went into package manager and disabled Unity Analytics under Build In packages and the errors came up. All similar to to this one,

```
Library\PackageCache\com.unity.film-internal-utilities@0.18.4-preview\Runtime\Scripts\Analytics\AnalyticsSender.cs(39,9): error CS1069: The type name 'AnalyticsResult' could not be found in the namespace 'UnityEngine.Analytics'. This type has been forwarded to assembly 'UnityEngine.UnityAnalyticsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' Enable the built in package 'Unity Analytics' in the Package Manager window to fix this error.
```

**Comment by sindharta** [comment] 2023-05-30 11:21
> So, is the shader supposed to work now even if the analytics is disabled? I still get the error message from film internal.
> UTS 0.9.4-preview, Unity 2022.2.19.

@plyoung Can you please let us know the intention of disabling Unity Analytics via Package Manager as you mentioned above ?

**Comment by plyoung** [comment] 2023-05-31 11:13
> > So, is the shader supposed to work now even if the analytics is disabled? I still get the error message from film internal.
> > UTS 0.9.4-preview, Unity 2022.2.19.
> 
> @plyoung Can you please let us know the intention of disabling Unity Analytics via Package Manager as you mentioned above ?

I just normally disable anything not used by the game, especially things like analytics since everyone is so privacy concerned these days. I do leave the analytics package on now and simply disable it via the API. Just thought it strange that shaders would create a  requirement in games to have analytics on for example and it now blocking me to disable such a package in the project.

**Comment by sindharta** [comment] 2023-06-01 02:54
So, this error caused by disabling Unity Analytics via Package Manager seems to be a bug in Unity.
To get around this, you can disable Analytics via the Preferences page as [mentioned above](https://github.com/Unity-Technologies/com.unity.toonshader/issues/289#issuecomment-1565376530).

![disable-analytics](https://github.com/Unity-Technologies/com.unity.toonshader/assets/7379311/e5ec662a-3f0a-449b-97bd-7890efa63883)

> Just thought it strange that shaders would create a requirement in games to have analytics on for example

We collect aggregated analytics data to measure the usage of ToonShader in projects, which will allow us to better allocate resources in the future.

**Comment by plyoung** [comment] 2023-06-04 12:16
Toggling "Disable Editor Analytics" does nothing for this error message when the Unity Analytics Package is disabled. Not sure if you were pointing out to toggle there or not? Well, not in 2022.2.19. Will be upgrading project to LTS later in week. 

![01](https://github.com/Unity-Technologies/com.unity.toonshader/assets/837362/52f44156-9794-4430-be29-ba526a15b4c3)
![02](https://github.com/Unity-Technologies/com.unity.toonshader/assets/837362/dc3487d5-920a-48e7-8a22-9d278794897f)

**Comment by sindharta** [comment] 2023-06-05 02:14
> Toggling "Disable Editor Analytics" does nothing for this error message when the Unity Analytics Package is disabled

If you have already checked "Disable Editor Analytics", then you don't need to disable Analytics in the Package Manager to achieve what you want, which is disabling Analytics.

**Comment by H3idi-X** [comment] 2023-06-20 01:20
Thank you for your inquiry.
We have resolved this issue and will close it.

**Closed** 2023-06-22 22:26 UTC
